export const START_AUTHENTICATION = "@auth/start_authentication"
export const AUTHENTICATION_SUCCESS = "@auth/authentication_success"
export const AUTHENTICATION_FAILED = "@auth/authentication_failed"
export const SET_AUTHENTICATION = "@auth/set_authentication"
export const SET_MESSAGE = "@auth/set_message"