export const TOOGLE_LOADING =  "@product/toogle_loading"
export const SET_PRODUCTS =  "@product/set_products"
export const FILTER_PRODUCTS =  "@product/filter_products"
export const GET_FIRST_LOADED =  "@product/get_first_loaded"
export const DEL_PRODUCT =  "@product/del_product"
export const SET_PRODUCT =  "@product/set_product"
export const TOOGLE_MODAL_LOADING =  "@product/toogle_modal_loading"